services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        volumes:
            - .:/var/www
        entrypoint: /entrypoint.sh
        networks:
            - laravel
        expose:
            - 9000

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
